#!/usr/bin/env node
/**
 * setup.js
 * ─────────────────────────────────────────────────────────
 * Reads your .env file and generates config.js so the
 * browser can access environment variables without
 * ever exposing them in source code committed to GitHub.
 *
 * Usage:
 *   node setup.js
 *
 * Run this once after cloning, and again whenever you
 * change a value in your .env file.
 *
 * Requires Node.js v18+ (no npm install needed — uses
 * only built-in fs and path modules).
 * ─────────────────────────────────────────────────────────
 */

const fs   = require('fs');
const path = require('path');

const ENV_FILE    = path.join(__dirname, '.env');
const CONFIG_FILE = path.join(__dirname, 'config.js');

/* ── Check .env exists ───────────────────────────────── */
if (!fs.existsSync(ENV_FILE)) {
  console.error('\n  ✖  .env not found.');
  console.error('     Copy the template first:\n');
  console.error('       cp .env.example .env\n');
  console.error('     Then fill in your API key and re-run:\n');
  console.error('       node setup.js\n');
  process.exit(1);
}

/* ── Parse .env ──────────────────────────────────────── */
function parseEnv(filePath) {
  const lines = fs.readFileSync(filePath, 'utf8').split('\n');
  const env   = {};

  for (const line of lines) {
    const trimmed = line.trim();

    // Skip blank lines and comments
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;

    const key = trimmed.slice(0, eqIdx).trim();
    let   val = trimmed.slice(eqIdx + 1).trim();

    // Strip surrounding quotes if present  ("value" or 'value')
    if ((val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }

    env[key] = val;
  }
  return env;
}

const env = parseEnv(ENV_FILE);

/* ── Validate required keys ──────────────────────────── */
const REQUIRED = ['API_NINJAS_KEY'];
const missing  = REQUIRED.filter(k => !env[k] || env[k] === 'your_api_key_here');

if (missing.length) {
  console.warn('\n  ⚠  The following keys are not set in your .env:\n');
  missing.forEach(k => console.warn(`       ${k}`));
  console.warn('\n     config.js will be generated but API calls will be skipped.');
  console.warn('     The app will still work using the built-in seed pool.\n');
}

/* ── Write config.js ─────────────────────────────────── */
// Only expose keys the browser actually needs.
// Do NOT dump the entire env object — only allowlisted keys.
const ALLOWLIST = ['API_NINJAS_KEY'];

const exposed = {};
for (const key of ALLOWLIST) {
  exposed[key] = env[key] || '';
}

const output = `/* ─────────────────────────────────────────────────────
   config.js  —  AUTO-GENERATED by setup.js
   Do NOT edit this file directly.
   Do NOT commit this file to git  (.gitignore covers it).

   Regenerate any time with:   node setup.js
   ───────────────────────────────────────────────────── */
window.ENV = ${JSON.stringify(exposed, null, 2)};
`;

fs.writeFileSync(CONFIG_FILE, output, 'utf8');

console.log('\n  ✔  config.js generated successfully.\n');
console.log('     Keys exposed to browser:\n');
for (const [k, v] of Object.entries(exposed)) {
  const display = v ? `${'*'.repeat(Math.min(v.length, 6))}…  (${v.length} chars)` : '(empty)';
  console.log(`       ${k.padEnd(24)} ${display}`);
}
console.log('\n     Open index.html in your browser (or run a local server) to start.\n');
